apiVersion: v1
kind: Service
metadata:
  name: {{ include "animal-picture-app.fullname" . }}
  labels:
    {{- include "animal-picture-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort | default nil }}
  selector:
    {{- include "animal-picture-app.selectorLabels" . | nindent 4 }}
